//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOFA.StockManagement.Presentation.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOFA.StockManagement.Presentation.UI.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة &quot;{0}&quot; و &quot;{1}&quot; غير متماثلتان EN.
        /// </summary>
        public static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة &quot;{0}&quot; ليست عنوان بريد الكترونى صحيح EN.
        /// </summary>
        public static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة &quot;{0}&quot; يجب ان تكون تاريخ. EN.
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة &quot;{0}&quot; يجب ان تكون رقم. EN.
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة &apos;{0}&apos; غير صحيحة. EN.
        /// </summary>
        public static string InvalidPropertyValue {
            get {
                return ResourceManager.GetString("InvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو كلمة السر غير صحيحة EN.
        /// </summary>
        public static string Login_Invalid {
            get {
                return ResourceManager.GetString("Login_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تأكيد بريدك الألكترونى رجاءً راجع بريدك او &lt;a href=&quot;{0}&quot;&gt;أعد ارسال بريد التاكيد&lt;/a&gt; EN.
        /// </summary>
        public static string Login_MailNotConfimed {
            get {
                return ResourceManager.GetString("Login_MailNotConfimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة &quot;{0}&quot; لابد ان تكون على الأقل &quot;{1}&quot; حروف EN.
        /// </summary>
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid value in the {1}..
        /// </summary>
        public static string ModelBinding_AttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_AttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the {0} is not specified..
        /// </summary>
        public static string ModelBinding_MissingBindRequiredValue {
            get {
                return ResourceManager.GetString("ModelBinding_MissingBindRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required..
        /// </summary>
        public static string ModelBinding_MissingKeyOrValue {
            get {
                return ResourceManager.GetString("ModelBinding_MissingKeyOrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request must have a body..
        /// </summary>
        public static string ModelBinding_MissingRequestBodyRequiredValue {
            get {
                return ResourceManager.GetString("ModelBinding_MissingRequestBodyRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not valid..
        /// </summary>
        public static string ModelBinding_NonPropertyAttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_NonPropertyAttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not valid..
        /// </summary>
        public static string ModelBinding_NonPropertyUnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_NonPropertyUnknownValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a number..
        /// </summary>
        public static string ModelBinding_NonPropertyValueMustBeANumber {
            get {
                return ResourceManager.GetString("ModelBinding_NonPropertyValueMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the {0} is not valid..
        /// </summary>
        public static string ModelBinding_UnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_UnknownValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not valid..
        /// </summary>
        public static string ModelBinding_ValueIsInvalid {
            get {
                return ResourceManager.GetString("ModelBinding_ValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a number..
        /// </summary>
        public static string ModelBinding_ValueMustBeANumber {
            get {
                return ResourceManager.GetString("ModelBinding_ValueMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required input..
        /// </summary>
        public static string ModelBinding_ValueMustNotBeNull {
            get {
                return ResourceManager.GetString("ModelBinding_ValueMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain digits (0-9).
        /// </summary>
        public static string PasswordValidator_PasswordRequireDigit {
            get {
                return ResourceManager.GetString("PasswordValidator_PasswordRequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain lowercase letters (&apos;a&apos;-&apos;z&apos;).
        /// </summary>
        public static string PasswordValidator_PasswordRequireLower {
            get {
                return ResourceManager.GetString("PasswordValidator_PasswordRequireLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain non alphanumeric character.
        /// </summary>
        public static string PasswordValidator_PasswordRequireNonLetterOrDigit {
            get {
                return ResourceManager.GetString("PasswordValidator_PasswordRequireNonLetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain uppercase letters (&apos;A&apos;-&apos;Z&apos;).
        /// </summary>
        public static string PasswordValidator_PasswordRequireUpper {
            get {
                return ResourceManager.GetString("PasswordValidator_PasswordRequireUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too short.
        /// </summary>
        public static string PasswordValidator_PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordValidator_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قمية &quot;{0}&quot; ليست رقم هاتف صحيح EN.
        /// </summary>
        public static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة &apos;{0}&apos; غير ملائمة لـ  &quot;{1}&quot;. EN.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must match the regular expression &apos;{1}&apos;..
        /// </summary>
        public static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}.
        /// </summary>
        public static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1} and a minimum length of {2}..
        /// </summary>
        public static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى سبق ادخاله من قبل EN.
        /// </summary>
        public static string ValidateEmail_DuplicateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى غير صحيح EN.
        /// </summary>
        public static string ValidateEmail_InvalidEmail {
            get {
                return ResourceManager.GetString("ValidateEmail_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى اقل من المسموح EN.
        /// </summary>
        public static string ValidateEmail_PropertyTooShort {
            get {
                return ResourceManager.GetString("ValidateEmail_PropertyTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدخول موجود من قبل EN.
        /// </summary>
        public static string ValidateUserName_DuplicateName {
            get {
                return ResourceManager.GetString("ValidateUserName_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدخول غير صحيح EN.
        /// </summary>
        public static string ValidateUserName_InvalidUserName {
            get {
                return ResourceManager.GetString("ValidateUserName_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدخول اقل من المسموح EN.
        /// </summary>
        public static string ValidateUserName_PropertyTooShort {
            get {
                return ResourceManager.GetString("ValidateUserName_PropertyTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; do not match..
        /// </summary>
        public static string Validator_CompareAttribute {
            get {
                return ResourceManager.GetString("Validator_CompareAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid credit card number..
        /// </summary>
        public static string Validator_CreditCardAttribute {
            get {
                return ResourceManager.GetString("Validator_CreditCardAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date..
        /// </summary>
        public static string Validator_DataTypeAttribute_Currency {
            get {
                return ResourceManager.GetString("Validator_DataTypeAttribute_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date..
        /// </summary>
        public static string Validator_DataTypeAttribute_Date {
            get {
                return ResourceManager.GetString("Validator_DataTypeAttribute_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة {0} غير مطابقة لبريد الكترونى EN.
        /// </summary>
        public static string Validator_EmailAddressAttribute {
            get {
                return ResourceManager.GetString("Validator_EmailAddressAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field only accepts files with the following extensions: {1}.
        /// </summary>
        public static string Validator_FileExtensionsAttribute {
            get {
                return ResourceManager.GetString("Validator_FileExtensionsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a maximum length of &apos;{1}&apos;..
        /// </summary>
        public static string Validator_MaxLengthAttribute {
            get {
                return ResourceManager.GetString("Validator_MaxLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a minimum length of &apos;{1}&apos;..
        /// </summary>
        public static string Validator_MinLengthAttribute {
            get {
                return ResourceManager.GetString("Validator_MinLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid phone number..
        /// </summary>
        public static string Validator_PhoneAttribute {
            get {
                return ResourceManager.GetString("Validator_PhoneAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        public static string Validator_RangeAttribute {
            get {
                return ResourceManager.GetString("Validator_RangeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must match the regular expression &apos;{1}&apos;..
        /// </summary>
        public static string Validator_RegularExpressionAttribute {
            get {
                return ResourceManager.GetString("Validator_RegularExpressionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string Validator_RequiredAttribute {
            get {
                return ResourceManager.GetString("Validator_RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        public static string Validator_StringLengthAttribute {
            get {
                return ResourceManager.GetString("Validator_StringLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1} and a minimum length of {2}..
        /// </summary>
        public static string Validator_StringLengthAttributeWithMin {
            get {
                return ResourceManager.GetString("Validator_StringLengthAttributeWithMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid fully-qualified http, https, or ftp URL..
        /// </summary>
        public static string Validator_UrlAttribute {
            get {
                return ResourceManager.GetString("Validator_UrlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة {0} لابد ان تطابق نمط رقمى EN.
        /// </summary>
        public static string Validator_ValueMustBeANumber {
            get {
                return ResourceManager.GetString("Validator_ValueMustBeANumber", resourceCulture);
            }
        }
    }
}
